
/*This has all already been done on dev manually but needs to be part of the update process.  


Step 1a If the table HTB_ISA_ONS_OSLAUA_TO_USE exists then delete it.*/
drop table if exists HTB_ISA_ONS_DATA

SELECT S.* 
INTO HTB_ISA_ONS_DATA
FROM ONS_DATA s
JOIN ( SELECT DISTINCT BR_PropertyPostcode
        FROM HTB_ISA_Transformed_BonusRequests) b
ON s.PCDS_CON = b.BR_PropertyPostcode


--Create an index on it. 

CREATE NONCLUSTERED INDEX HTB_ISA_ONS_DATA_IDX ON HTB_ISA_ONS_DATA
(
       PCDS_CON ASC
)


DROP TABLE IF EXISTS HTB_ISA_ONS_OSLAUA_TO_USE
--Step 1b Create the table HTB_ISA_ONS_OSLAUA_TO_USE.

  SELECT PCDS_OUTER, oslaua, USE_THIS_OSLAUA, NUMBER_OF_POSTCODES
  INTO HTB_ISA_ONS_OSLAUA_TO_USE
  FROM 
  ( SELECT PCDS_OUTER, oslaua, USE_THIS_OSLAUA, tval NUMBER_OF_POSTCODES,
          MIN(oslaua)  OVER (PARTITION BY PCDS_OUTER) min_os
FROM (
SELECT t2.*, CASE WHEN MAX( tval) OVER (PARTITION BY PCDS_OUTER) = tval
                   THEN 'Y'
                              ELSE 'N'
                       END USE_THIS_OSLAUA
FROM (
  SELECT  PCDS_OUTER, oslaua, COUNT(pcds_con) tval
  FROM HTB_ISA_ONS_DATA a
    GROUP BY PCDS_OUTER, oslaua ) t2) t3
WHERE    USE_THIS_OSLAUA = 'Y') r
WHERE min_os = oslaua

--Step 1c Create the index on HTB_ISA_ONS_OSLAUA_TO_USE.

CREATE NONCLUSTERED INDEX [IDX_OSLAUA_TO_USE] ON  HTB_ISA_ONS_OSLAUA_TO_USE
(
       PCDS_OUTER, oslaua ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


--Step 2a If HTB_ISA_ONS_OSLAUA_TO_USE_CHECK exists then delete it. 
DROP TABLE IF EXISTS HTB_ISA_ONS_OSLAUA_TO_USE_CHECK
--Step 2b Use HTB_ISA_ONS_OSLAUA_TO_USE to create it. 

SELECT OD2.oslaua OD2_oslaua, OD.*
INTO  HTB_ISA_ONS_OSLAUA_TO_USE_CHECK
        FROM HTB_ISA_ONS_DATA OD 
              JOIN HTB_ISA_ONS_OSLAUA_TO_USE OD2
              ON OD.PCDS_OUTER = OD2.PCDS_OUTER

--Step 3c Create the index on HTB_ISA_ONS_OSLAUA_TO_USE_CHECK.


CREATE NONCLUSTERED INDEX [IDX_OSLAUA_TO_USE_CHECK] ON  HTB_ISA_ONS_OSLAUA_TO_USE_CHECK
(
       PCDS_CON , OD2_oslaua ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
